cds:
  security:
    authentication: none
    mock:
      users:
        - name: "test-user"
          password: "1234"
  datasource:
    model: [db/schema.cds]
    db:
      kind: sql
      credentials:
        url: jdbc:h2:mem:transportdb;DB_CLOSE_DELAY=-1
        driver: org.h2.Driver
        username: sa
        password: ""
  
  odata:
    path: /odata/v4
    draft.enabled: true

  deploy:
    target: cf
    service: transport-service

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate

management:
  endpoints.web.exposure.include: health,info

logging:
  level:
    root: INFO
    com.sap.cds: DEBUG

